name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python base
      uses: actions/setup-python@v4
      with:
        python-version-file: .python-version
        cache: 'pip'
    - name: Install base packages
      run: pip install -r .github/requirements.txt
    - name: Set up Python venv
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install venv packages
      run: poetry install --no-interaction --no-root
    - run: poetry run mkdocs gh-deploy --force
