name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Load cached local for Poetry
        id: cached-poetry-install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: local-${{ hashFiles('**/pyproject.toml') }}
      - name: Install Poetry
        if: steps.cached-poetry-install.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install packages
        run: poetry install --no-interaction --no-root
      - run: poetry run mkdocs gh-deploy --force
