name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Load cached local for Poetry
        id: cached-poetry-install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: local-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.toml') }}
      - name: Install Poetry
        if: steps.cached-poetry-install.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Load cached virtual environment
        id: cached-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install packages
        if: steps.cached-venv.outputs.cache-hit == 'false'
        run: poetry install --no-interaction
      - run: mkdocs gh-deploy --force