name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }} venv
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - run: poetry env use python${{ matrix.python-version }}
    - name: Install venv packages
      run: poetry install --no-interaction --no-root
    - name: Test
      run: poetry run pytest --cov --cov-report=xml
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
