name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    env:
      POETRY_HOME: /home/runner/poetry_home

    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download setup-poetry.py
      run: curl -sSL https://install.python-poetry.org > setup-poetry.py
    - name: Load cached Poetry installation
      uses: actions/cache@v3
      with:
        path: /home/runner/poetry_home
        key: poetry-${{ hashFiles('setup-poetry.py') }}
    - name: Install Poetry
      run: python3 setup-poetry.py
    - run: /home/runner/poetry_home/bin/poetry config virtualenvs.in-project true
    - name: Load cached virtual environment
      uses: actions/cache@v3
      with:
        path: .venv
        key: poetry.lock-${{ matrix.python-version }}-${{ hashFiles(poetry.lock) }}
        restore-keys: |
          - poetry.lock-${{ matrix.python-version }}-
    - run: /home/runner/poetry_home/bin/poetry install --no-interaction
    - run: /home/runner/poetry_home/bin/poetry run pytest
