name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Load cached Poetry installation
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: poetry-${{  hashFiles('~/.local')  }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - run: ls ~/.local/bin
    - run: echo "${{ hashFiles('**/.local/bin/poetry') }}"
    - run: poetry config virtualenvs.in-project true
    - name: Load cached virtual environment
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{  hashFiles('.venv/*')  }}
    - run: poetry install --no-interaction
    - run: poetry run pytest
