name: Update Dependencies

on:
  schedule:
    - cron:  '0 6 1 * *' # at 06:00 on the first day of every month
  workflow_dispatch: # enables manual trigger

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Update dependencies
        run: |
          pip install poetryup
          poetryup
          if [ -n "$(git status --porcelain)" ]; then
            # working tree NOT clean, bump project version
            poetry version patch
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            token: ${{ secrets.PAT }}
            commit-message: Update dependencies
            title: Update dependencies
            branch: update-dependencies
            delete-branch: true
