name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 1 * *' # at 06:00 on the first day of every month

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version-file: .python-version
          cache: 'poetry'
      - run: poetry env use '${{ steps.setup-python.outputs.python-path }}'
      - name: Update dependencies
        run: |
          pip install poetryup
          poetryup
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: Update dependencies
            title: Update dependencies
            branch: update-dependencies
            body: ''
            delete-branch: true
